import React from 'react';
import { NotificationProvider } from '../context/NotificationContext';
import NotificationContainer from '../components/NotificationContainer';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <NotificationProvider>
        <body>
          {children}
          <NotificationContainer />
        </body>
      </NotificationProvider>
    </html>
  )
}
